FROM arm32v7/eclipse-temurin:11-jre

RUN mkdir /deployments

ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

COPY maven/quarkus-app/* /deployments/
CMD java $JAVA_OPTS -jar /deployments/quarkus-run.jar
