FROM eclipse-temurin:17-jre


ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

COPY maven/quarkus-app /opt/
CMD java $JAVA_OPTS -jar /opt/quarkus-run.jar
